=== AchinoTsitsi/XML/TP XML/etudiant.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- Définition du type pour la date de naissance (supérieure à 1990) -->
<xsd:simpleType name="date_naissance">
  <xsd:restriction base="xsd:date">
    <xsd:minInclusive value="1990-01-01"/>
  </xsd:restriction>
</xsd:simpleType>

<!-- Définition du type pour les notes entre 0 et 20 -->
<xsd:simpleType name="noteType">
  <xsd:restriction base="xsd:decimal">
    <xsd:minInclusive value="0"/>
      <xsd:maxInclusive value="20"/>
  </xsd:restriction>
</xsd:simpleType>

<!-- Définition du type pour le numéro de téléphone -->
<xsd:simpleType name="telephoneType">
  <xsd:restriction base="xsd:string">
    <xsd:pattern value="0 [0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}"/>
  </xsd:restriction>
</xsd:simpleType>

<!-- Email -->
<xsd:simpleType name="emailAddress">
  <xsd:restriction base="xsd:string">
    <xsd:pattern value="[^@]+@[^\.]+\..+"/>
  </xsd:restriction>
</xsd:simpleType>


<xsd:element name="etudiant" >
<xsd:complexType>
<xsd:sequence>
<xsd:element name="nom" type="xsd:string"/>
<xsd:element name="prenom" type="xsd:string" />
<xsd:element name="date_naissance" type="date_naissance"/>
<xsd:element name="note"  maxOccurs="unbounded">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="td" type="noteType"  minOccurs="0"/>
<xsd:element name="tp" type="noteType" minOccurs="0"/>
<xsd:element name="exam" type="noteType" minOccurs="0"/>
</xsd:sequence>
<xsd:attribute name="module" type="xsd:string" use="required"/>
</xsd:complexType>
</xsd:element>
</xsd:sequence>
<xsd:attribute name="numNat" type="xsd:long" use="optional"/>
<xsd:attribute name="mat" type="xsd:string" use="required"/>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== AchinoTsitsi/XML/TP XML/etudiant.xml
<?xml version="1.0" encoding="UTF-8"?>
<etudiant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="etudiant.xsd" mat="E12345">
<nom>Ait Allaoua</nom>
    <prenom>Walid</prenom>
    <date_naissance>2004-08-08</date_naissance>
    <note module="DSS">
        <td>15.5</td>
        <tp>16.0</tp>
        <exam>14.0</exam>
    </note>
</etudiant>
