=== AchinoTsitsi/XML/TP XML/exo1.dtd
<!ELEMENT conversation (note+)>
<!ELEMENT note (to?, from?, heading?, body?)>
<!ATTLIST note date CDATA #IMPLIED>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>

=== AchinoTsitsi/XML/TP XML/exo1.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE conversation SYSTEM "exo1.dtd">
<conversation>
    <!-- this is a note --> 
    <note date="3 janvier"> 
        <to>Bob</to> 
        <from>Alice</from> 
        <heading>Reminder</heading> 
        <body>Don't forget the book!</body> 
    </note> 

    <!-- this is another note --> 
    <note date="5 janvier"> 
        <to>Alice</to> 
        <from>Bob</from> 
        <body>don’t worry</body> 
    </note> 
</conversation>
