=== AchinoTsitsi/XML/TP XML/test2.dtd
<!ELEMENT canvas (polygone*, cercle*)>

<!ELEMENT polygone (nom)>
<!ATTLIST polygone
    nbrcote CDATA #REQUIRED
    etat (vide | pleine | hachuree) #REQUIRED
    zorder CDATA #REQUIRED>

<!ELEMENT cercle (nom)>
<!ATTLIST cercle
    etat (vide | pleine | hachuree) #REQUIRED
    zorder CDATA #REQUIRED>

<!ELEMENT nom (#PCDATA)>

=== AchinoTsitsi/XML/TP XML/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canvas SYSTEM "test2.dtd">
<canvas>
  <polygone nbrcote="4" etat="vide" zorder="1">
    <nom>Rectangle</nom>
  </polygone>
  <cercle etat="vide" zorder="2">
    <nom>Cercle</nom>
  </cercle>
  <polygone nbrcote="6" etat="vide" zorder="3">
    <nom>Polygone</nom>
  </polygone>
  <polygone nbrcote="3" etat="pleine" zorder="4">
    <nom>Triangle</nom>
  </polygone>
</canvas>
